### ISSUE TITLE
late_fusion.py does not work

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#1]
late_fusion.py does not work because you cannot cat two tensors whose shapes are different from each other. The dimensions of f and g are (10,1,14,14) and (10,1,224,224) in line 20.

I think you should not comment out in line 19.
You have to change the dimension of f from (10,1,14,14) to (10,1,224,224) by upsampling.

**Comment by hyf015** [comment]
Yes, it is commented. The code has been updated, maybe you are using a version before update.

**Comment by kazucmpt** [comment]
Thank you very much.
