### ISSUE TITLE
Should we resize input files by ourselves?

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#11]
By running dataset_preprocessing.py, we can generate gazemap and it will be resized (224,224) in dataset_preprocessing.py. 

But in dataset_preprocessing.py, input image files are not resized. Do we have to resize input image files by ourselves? or by running gaze_full.py, will input image files be resized (224,224) automatically?

**Comment by hyf015** [comment]
Yes, it's better if you resize them.

**Comment by kazucmpt** [comment]
Thank you.
