### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Tushar-N** [hyf015/egocentric-gaze-prediction#12]
Would it be possible to provide pretrained models from your experiments which can be used directly for evaluation? A script to use the pretrained models to generate saliency maps for a video would also be very helpful.

Thanks for putting up your code! :)

**Comment by hyf015** [comment]
Thank you for your interest. Actually, our model is trained separately, so I think it would be confusing to put each pre-trained model and intermediate outputs. I'll first upload a pre-trained model for saliency prediction only and it would be easy to use.

**Comment by kazucmpt** [comment]
Good!
It will help many researchers.

**Comment by Tushar-N** [comment]
> I'll first upload a pre-trained model for saliency prediction only and it would be easy to use.

Great, thank you!

**Comment by Tushar-N** [comment]
Just wanted to check in on this issue. Has there been any progress?

**Comment by hyf015** [comment]
You can see the model in readme now. I haven't prepared a script for using it yet, but that should be simple.

**Comment by Tushar-N** [comment]
Thanks again! I really appreciate the help. I am having a bit of trouble with inference though. I can load the model just fine, but there are details about preprocessing and inputs that aren't obvious to be from the scripts, and it would be helpful if a single script that just has the skeleton with an example is provided.

```
from SP import SP
sp = SP(pretrained_spatial='pretrained_sp.pth.tar',  pretrained_temporal='save/pretrained_sp.pth.tar')
sp.model.load_state_dict(torch.load('pretrained_sp.pth.tar')['state_dict'])
```

This is as far as I got before I realized I don't know what the expected inputs are
```
# is rgb a (B, 3, 224, 224) tensor?
# is Flow a (B, 2, 224, 224) tensor?
output = sp.model(rgb, flow) 
```

Thanks!

**Comment by hyf015** [comment]
Flow is a (B, 20, 224,224)

Tushar Nagarajan <notifications@github.com>于2018年10月9日 周二上午2:13写道：
