### ISSUE TITLE
The number of data of grand truth images and RGB images are not the same as each other.

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#13]
We read your dataset_preprocessing.py and understood how to generate ground truth and fixation.txt.
But the number of data of grand truth isn't same as that of RGB images.

For example, Alireza_American.avi in GTEA datasets plus has 19824 frames, but dataset_preprocessing.py generate 19847 images. 

We think it causes error in gaze_full.py. How did you solve it?

**Comment by hyf015** [comment]
Other files have similar problems. Some videos are longer than gaze tracking data and some are shorter. I use the shorter one for reference and manually delete some extra files.

**Comment by kazucmpt** [comment]
Thank you.
