### ISSUE TITLE
We have to delete 10 grand truth images each video.

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#14]
To train SP module, we have to delete below files.

gtea_gt/Alireza_American_000000.jpg,…,Alireza_American_000010.jpg
gtea_gt/Alireza_Burger_000000.jpg,…,Alireza_Burger_000010.jpg
   ・
   ・
   ・
gtea_gt/Yin_Turkey_000000.jpg,…,Yin_Turkey_000010.jpg

I recommend you to write this important information in README.md.

**Comment by hyf015** [comment]
Yes, that's true. Actually, I deleted the first 100 images in my experiment.

**Comment by kazucmpt** [comment]
Why the first 100 images? 
I think the first 10 images are enough.

**Comment by hyf015** [comment]
Usually, the first few frames are useless, maybe some instructions to the recorder.

**Comment by mujn1461** [comment]
Hi, sorry to comment on this long-closed issue! But just to double-check that besides deleting the first 100 ground truth images, we should also delete the first 100 input images and the first 100 entries in every fixsac txt file as well? Thank you!
