### ISSUE TITLE
We cannot go into SP module during testing

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#15]
You wrote like below in gaze_full.py

if args.train_sp:
　　sp = SP(lr=args.lr, loss_save=args.sp_save_img, save_name=args.save_sp,...)
　　sp.train()
　　 args.pretrained_model = os.path.join(args.save_path, args.save_sp)

But it should be 

sp = SP(lr=args.lr, loss_save=args.sp_save_img, save_name=args.save_sp,...)
if args.train_sp:
　　 sp.train()
　　args.pretrained_model = os.path.join(args.save_path, args.save_sp)
else:
　　sp.testSP()

**Comment by hyf015** [comment]
You can modify as you wish, I did this because sometimes I only want to use trained SP module without training or testing.

**Comment by kazucmpt** [comment]
Thank you.
How about LSTM? If I only want to use trained LSTM module without training, I should modify

att = AT(pretrained_model =args.pretrained_model, ...)
if args.train_lstm:
　att.train()
else:
　att.testLSTM()

right?

**Comment by hyf015** [comment]
Yes, sure.

**Comment by kazucmpt** [comment]
I understood. Thank you.
