### ISSUE TITLE
How to run testing?

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#16]
We have finished training. So next, we want to test. In order to test, should we run

`python3 gaze_full.py --flowPath ../gtea_imgflow_pre --imagePath ../gtea_images --fixsacPath ../fixsac --gtPath ../gtea_gts --pretrained_model save/best_SP.pth.tar --pretrained_lstm save/best_lstm.pth.tar --pretrained_late save/best_late.pth.tar --extract_lstm --extract_late`

Is it correct?
In this case, will SP module work?

**Comment by hyf015** [comment]
If you have finished training everything, files for testing should have already been extracted. Thus you don't need to extract the intermediate files again.

**Comment by kazucmpt** [comment]
I want to do only testing. But without modifying gaze_full.py as I said[ in other question](https://github.com/hyf015/egocentric-gaze-prediction/issues/15), I think it does not work, right?

**Comment by hyf015** [comment]
I think it's a good idea to modify the scripts for your purpose.

**Comment by kazucmpt** [comment]
Thank you.
But why don't you modify it?
It helps many people.

**Comment by hyf015** [comment]
Because I'm also using this repo for other purposes, sorry.

**Comment by kazucmpt** [comment]
I see.
