### ISSUE TITLE
Where are Gt^s and Gt^a saved?

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#17]
I want to know where Gt^s and Gt^a will be saved.

I think Gt^a will be saved in ../new_feat.
And predicted gaze image will be generated in ../new_pred.

Where can we find Saliency map Gt^a?

**Comment by hyf015** [comment]
Gt^a is not saved in this code. You can write your own code for saving it.

**Comment by kazucmpt** [comment]
So, Gt^s will be saved in ../new_feat and predicted gaze image will be generated in ../new_pred.
Is it correct?

**Comment by hyf015** [comment]
Oh, sorry I was wrong. Gt^a is in ../new_feat, and Gt^s is in ../new_pred.

**Comment by kazucmpt** [comment]
Thank you. So, predicted gaze image will not be saved in your program, right?

**Comment by hyf015** [comment]
The final result of LF is not saved.

**Comment by kazucmpt** [comment]
I see. 
Thank you.
