### ISSUE TITLE
sigma of gaussian filter used in auc

### ISSUE THREAD

**Issue by Luisaply** [hyf015/egocentric-gaze-prediction#18]
In 'utils.py' you have used a gaussian filter to get the auc.

> z = ndimage.filters.gaussian_filter(z, 14)

Is there a reason to set sigma to 14?

**Comment by hyf015** [comment]
If you see the [closed issue](https://github.com/hyf015/egocentric-gaze-prediction/issues/5), the original variance we use is 70. 14 is one-fifth of 70, and corresponds to the input size of the network.
