### ISSUE TITLE
How to train fixation state predictor without teaching data in GTEA Gaze

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#2]
I have a question about your paper.
According to your paper, you use GTEA Gaze dataset and GTEA Gaze Puls dataset.
But it seems that information of fixation or saccade are not included in GTEA Gaze while included in GTEA Gaze Plus.

So, do you train fixation state predictor by only GTEA Gaze Plus??
I think we cannot train fixation state predictor by GTEA Gaze dataset.

**Comment by hyf015** [comment]
We have the ground truth gaze data, so we computed fixation and saccade by ourselves.

**Comment by hyf015** [comment]
I've uploaded the script for calculation fixation state for GTEA Gaze dataset [here](https://github.com/hyf015/egocentric-gaze-prediction/blob/master/misc/gazedataset_gt.py).

**Comment by kazucmpt** [comment]
Thank you for uploading your code. I understand that : 
 When abs(g_{t-1}-g_{t} ) > Threshold, saccade 
 When abs(g_{t-1}-g_{t} ) < Threshold, fixation

abs means absolute value.
g_{t} is gaze point at t frame and two dimensional vector.

And threshold is sqrt(2500). Is my understanding correct??

**Comment by hyf015** [comment]
Right. I forgot the reference, I'll update the reference when I find it.

**Comment by kazucmpt** [comment]
Thank you.
I am waiting for your updating reference.

**Comment by hyf015** [comment]
we use definitions of fixations from Fathi et al. "Learning to Predict Gaze in Egocentric Video", which comes originally from  NYSTRÖM et al. "An adaptive algorithm for fixation, saccade, and glissade detection in eyetracking data".

**Comment by kazucmpt** [comment]
Thank you very much.
We recommend you to write such an important information in your paper.
