### ISSUE TITLE
There is an error in running the code dataset_preprocessing.py

### ISSUE THREAD

**Issue by mmppllhaha** [hyf015/egocentric-gaze-prediction#21]
First of all, thank you very much for the author's work and code.
There are some questions that I would like to ask when I run the code.

Your code: dataset_preprocessing.py can be used to convert coordinate points in the ground truth.txt file into saliency maps. But there are many times in the txt file that there are two or three gaze points in the same frame, as if your code does not determine the corresponding relationship between gaze points and frames, and the resulting saliency map may be incorrect.

Another question is why the following judgment should be made in the function "parsetxt"?
line 42：
“elif int(s[5]) not in nframe:
				if nframe[-1] + 1 == int(s[5]):
					if int(round(float(s[3]))) in range(1280) and int(round(float(s[4]))) in range(960):
						”
I look forward to your reply. Thank you very much.

**Comment by mmppllhaha** [comment]
I looked at the code carefully again and finally got it. When two coordinates are in the same frame, you get an average. Thank you very much.

**Comment by hyf015** [comment]
Sorry that I just saw it. Glad to know that the problem is solved.
