### ISSUE TITLE
Something wrong with directory structure.

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#3]
According to your README.md, directory structure should be like

path/to/images
path/to/opticalflow/images/flow/ …
path/to/gt/images

But in data/dataset_preprocessing.py in line from 80 to 85, you browse 

gtea_gaze/
gtea_flows/
gtea_images/
gtea_gts/
gtea_imgflow/

We have to create these folders to implement your python file but we do not know what kind of date should be in each folder. Would you explain correct directory structure?

**Comment by hyf015** [comment]
Sorry, the code for preprocessing is actually old. We first generate optical flow images from the videos (into folder gtea/imgflow), then put all images into the folder gtea_images/
in gtea_gaze/ files should be the txt files containing gaze ground truth from GTEA. [example](http://webshare.ipat.gatech.edu/coc-rim-wall-lab/web/afathi3/AwareHome/Yin/Yin_Pizza.txt)

gtea_gts/ contain all the ground truth image generated from gaze (x,y) positions.

'gtea_flows/' is useless.

**Comment by kazucmpt** [comment]
I understand. But I think you have to modify README.md. You wrote 

> Please download and extract all images into path/to/images. For the optical flow images, use dense flow to extract all optical flow images, and put them into path/to/opticalflow/images. 
> Put the ground truth gaze maps into path/to/gt/images.

But I guess correct sentences should be 

> Please download and extract all images into **../gtea_images**. For the optical flow images, use dense flow to extract all optical flow images, and put them into **../gtea_imgflow**. 
> Put the ground truth gaze maps into **../gtea_gts**

**Comment by hyf015** [comment]
Actually, I didn't recommend to use the code of datasetpreprocessing.py

If to put the images to another place, one can completely ignore my pre-processing code.

**Comment by kazucmpt** [comment]
O.K.

But I think you should write about that. Now, many people in my company are reading your README.md.
Everybody was confused about the directory structure.

Anyway, thank you so much. Your answers are really helpful to understand your paper.

**Comment by hyf015** [comment]
Thank you for your interest. I'll make it easier to read.

**Comment by zhangtongtong528** [comment]
>           According to your README.md, directory structure should be like
> path/to/images
> path/to/opticalflow/images/flow/ …
> path/to/gt/images
> But in data/dataset_preprocessing.py in line from 80 to 85, you browse
> gtea_gaze/
> gtea_flows/
> gtea_images/
> gtea_gts/
> gtea_imgflow/
> We have to create these folders to implement your python file but we do not know what kind of date should be in each folder. Would you explain correct directory structure?

excuse me,Is the data placed in the corresponding folder in image format or in TXT format?
