### ISSUE TITLE
What is the value of the variance of 2D Gaussian?

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#5]
> The ground truth gaze image is generated from the gaze data by pointing a 2d Gaussian at the gaze position. Put the ground truth gaze maps into path/to/gt/images. 

I want to generate the ground truth gaze map, so I need the value of the variance of 2d Gaussian. I could not find that in your paper. Would you tell us that value?

Thank you.

**Comment by hyf015** [comment]
For 1280x720 image I used a variance of 70.

**Comment by kazucmpt** [comment]
Thank you.

So after you generate the ground truth gaze images whose size are 1280×720, you resized the images 224×224 ?

**Comment by hyf015** [comment]
Yes, you are right.

kazucmpt <notifications@github.com>于2018年9月27日 周四下午8:57写道：

**Comment by kazucmpt** [comment]
I understood well.
Thank you very much.
