### ISSUE TITLE
Which directory structure is correct??

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#7]
We used dense flow to generate the input files.
But we want to know which directory structure is correct.

A.
gtea_imgflow/flow/Alireza_American/flow_x_00001.jpg,flow_x_00002.jpg,…,flow_y_00001.jpg,…

or

B.
gtea_imgflow/Alireza_American/flow_x_00001.jpg,flow_x_00002.jpg,…,flow_y_00001.jpg,…

As far as I can see your code, B is correct. But as far as I can see your README.md, A is correct.

Thank you.

**Comment by hyf015** [comment]
B is correct. As I said, the code for preprocessing is just for reference, don't be confused with it.

**Comment by kazucmpt** [comment]
Thank you for your modifying  README.md.

**Comment by zhangtongtong528** [comment]
>           B is correct. As I said, the code for preprocessing is just for reference, don't be confused with it.

Please,Is the format of other data the same as that of optical streaming folders?
