### ISSUE TITLE
We want to know some parameters of dense_flow.

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#8]
To generate input image files, you used [dense_flow](https://github.com/yjxiong/dense_flow/tree/opencv-3.1).
What were your parameters b and t?

**Comment by hyf015** [comment]
You can choose b and t by yourself. The important thing is to normalize optical flow images into between 0 and 1.

**Comment by kazucmpt** [comment]
We want to reproduce your experimental result.
We know we can choose b and t by ourselves as you said but we would like to know your parameter values.

**Comment by hyf015** [comment]
Sure, we use default parameters as dense flow.

**Comment by kazucmpt** [comment]
Which branch of dense flow did you use, master or opencv3-1?

The default values of the parameters are different.

**Comment by hyf015** [comment]
I used the master branch.

kazucmpt <notifications@github.com>于2018年10月2日 周二下午4:21写道：

**Comment by kazucmpt** [comment]
According to extract_flow_gpu.cpp, the default values of the parameters of the master branch are t=0 and b=15. But in README.md of the master branch of dense flow, 

> Usage
./extract_gpu -f test.avi -x tmp/flow_x -y tmp/flow_y -i tmp/image -b 20 -t 1 -d 0 -s 1 -o dir

You said you used the defult values. That means t=0 and b=15, right?

Thank you.

**Comment by hyf015** [comment]
Sorry for the confusion. I mean b is 20 and t is 1.

kazucmpt <notifications@github.com>于2018年10月2日 周二下午4:30写道：

**Comment by kazucmpt** [comment]
Thank you very much.

How many hours did you need to calculate optical flow by using GPU?
We had started to calculate the optical flow of GTEA dataset plus by using dense flow a few days ago. But the calculation is not finished yet. We use GTX-1070. 

It seems that it takes more than 3 hours in each avi file.

How about you? Did it take so many hours?

**Comment by hyf015** [comment]
Yes, it took a few days I remember...

**Comment by kazucmpt** [comment]
Thank you very much.
Your answers always help us.
