### ISSUE TITLE
Something wrong with browsing place in data/STdatas.py

### ISSUE THREAD

**Issue by kazucmpt** [hyf015/egocentric-gaze-prediction#9]
In data/STdatas.py in line, you wrote:

> if __name__ == '__main__':
        imgPath = '../gtea_imgflow'
        gtPath = '../gtea_gts'
         fixsacPath = '../fixsac'

But I guess it should be 

> if __name__ == '__main__':
        imgPath = '../../gtea_imgflow'
        gtPath = '../../gtea_gts'
         fixsacPath = '../fixsac'

Am I wrong?

**Comment by hyf015** [comment]
It depends on from which directory you run the code.

**Comment by kazucmpt** [comment]
Of course, you right.
Although, you suppose gtea_images and gtea_imgflow folders are in ../ in gaze_full.py,  you suppose gtea_images and gtea_imgflow are in other location in data/STdatas.py.

Being without a consistency is not good.

**Comment by hyf015** [comment]
Yes, that's true. My assumption is that people run their code in the main directory.
I'd appreciate it if there a suggestion on how to modify it.

**Comment by zhangtongtong528** [comment]
Hi! If I just want to get the saliency map of my video dataset, do I run STdatas.py for data processing and then SP.py?

**Comment by hyf015** [comment]
> Hi! If I just want to get the saliency map of my video dataset, do I run STdatas.py for data processing and then SP.py?

Sorry I missed this. I think you need to modify STdatas and then run SP.
